"""empty message

Revision ID: 0c52ab11359f
Revises: 
Create Date: 2020-11-08 16:43:37.640353

"""
from alembic import op
import sqlalchemy as sa
import dateutil


# revision identifiers, used by Alembic.
revision = '0c52ab11359f'
down_revision = None
branch_labels = None
depends_on = None

def create_venue_genre_dict(venue_id, genres):
    return [{"venue_id": venue_id, "genre":genre} for genre in genres]

def create_artist_genre_dict(artist_id, genres):
    return [{"artist_id": artist_id, "genre":genre} for genre in genres]

def parse_date_string(datestring):
    return dateutil.parser.parse(datestring)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    artist_table = op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('seeking_venue', sa.Boolean(), nullable=False),
    sa.Column('seeking_description', sa.String(), nullable=True, default = ''),
    sa.PrimaryKeyConstraint('id')
    )
    venue_table = op.create_table('venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('facebook_link', sa.String(), nullable=True),
    sa.Column('seeking_talent', sa.Boolean(), nullable=False),
    sa.Column('seeking_description', sa.String(), nullable=True, default = ''),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    artist_genre_tags = op.create_table('artist_genre_tags',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'genre')
    )
    show_table = op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('show_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    venue_genre_tags = op.create_table('venue_genre_tags',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'genre')
    )
    
    #============================= INSERT VENUE DATA===========================================
    venue_1={
    "id": 1,
    "name": "The Musical Hop",
    "address": "1015 Folsom Street",
    "city": "San Francisco",
    "state": "CA",
    "phone": "123-123-1234",
    "website": "https://www.themusicalhop.com",
    "facebook_link": "https://www.facebook.com/TheMusicalHop",
    "seeking_talent": True,
    "seeking_description": "We are on the lookout for a local artist to play every two weeks. Please call us.",
    "image_link": "https://images.unsplash.com/photo-1543900694-133f37abaaa5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60",
    }

    venue_2={
    "id": 2,
    "name": "The Dueling Pianos Bar",
    "address": "335 Delancey Street",
    "city": "New York",
    "state": "NY",
    "phone": "914-003-1132",
    "website": "https://www.theduelingpianos.com",
    "facebook_link": "https://www.facebook.com/theduelingpianos",
    "seeking_talent": False,
    'seeking_description': '',
    "image_link": "https://images.unsplash.com/photo-1497032205916-ac775f0649ae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80",
    }

    venue_3={
    "id": 3,
    "name": "Park Square Live Music & Coffee",
    "address": "34 Whiskey Moore Ave",
    "city": "San Francisco",
    "state": "CA",
    "phone": "415-000-1234",
    "website": "https://www.parksquarelivemusicandcoffee.com",
    "facebook_link": "https://www.facebook.com/ParkSquareLiveMusicAndCoffee",
    "seeking_talent": False,
    'seeking_description': '',
    "image_link": "https://images.unsplash.com/photo-1485686531765-ba63b07845a7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=747&q=80",
    }


    venue_genres_1 = create_venue_genre_dict(1, ["Jazz", "Reggae", "Swing", "Classical", "Folk"])
    venue_genres_2 = create_venue_genre_dict(2, ["Classical", "R&B", "Hip-Hop"])
    venue_genres_3 = create_venue_genre_dict(3, ["Rock n Roll", "Jazz", "Classical", "Folk"])




    
    op.bulk_insert(
        venue_table,
        [
            venue_1,
            venue_2,
            venue_3
        ]
    )
    
    op.bulk_insert(
        venue_genre_tags,
        venue_genres_1 + venue_genres_2 + venue_genres_3

    )

    #============================= INSERT ARTIST DATA===========================================
    artist_4={
    "id": 4,
    "name": "Guns N Petals",
    "city": "San Francisco",
    "state": "CA",
    "phone": "326-123-5000",
    "website": "https://www.gunsnpetalsband.com",
    "facebook_link": "https://www.facebook.com/GunsNPetals",
    "seeking_venue": True,
    "seeking_description": "Looking for shows to perform at in the San Francisco Bay Area!",
    "image_link": "https://images.unsplash.com/photo-1549213783-8284d0336c4f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=80",
    }

    artist_5={
    "id": 5,
    "name": "Matt Quevedo",
    "city": "New York",
    "state": "NY",
    "phone": "300-400-5000",
    "website": "",
    "facebook_link": "https://www.facebook.com/mattquevedo923251523",
    "seeking_venue": False,
    "seeking_description":'',
    "image_link": "https://images.unsplash.com/photo-1495223153807-b916f75de8c5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80",
    }

    artist_6={
        "id": 6,
        "name": "The Wild Sax Band",
        "city": "San Francisco",
        "state": "CA",
        "phone": "432-325-5432",
        "website": "",
        "facebook_link": None,
        "seeking_venue": False,
        "seeking_description":'',
        "image_link": "https://images.unsplash.com/photo-1558369981-f9ca78462e61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=794&q=80",
    }

    arist_genres_4 = create_artist_genre_dict(4, ["Rock n Roll"])
    arist_genres_5 = create_artist_genre_dict(5, ["Jazz"])
    arist_genres_6 = create_artist_genre_dict(6, ["Jazz", "Classical"])

    op.bulk_insert(
        artist_table,
        [
            artist_4,
            artist_5,
            artist_6
        ]
    )
    
    op.bulk_insert(
        artist_genre_tags,
        arist_genres_4 + arist_genres_5 + arist_genres_6

    )
    #============================= INSERT SHOW DATA===========================================
    
    show_data=[{
    "venue_id": 1,
    "artist_id": 4,
    "show_date": "2019-05-21T21:30:00.000Z"
    }, {
    "venue_id": 3,
    "artist_id": 5,
    "show_date": parse_date_string("2019-06-15T23:00:00.000Z")
    }, {
    "venue_id": 3,
    "artist_id": 6,
    "show_date": parse_date_string("2035-04-01T20:00:00.000Z")
    }, {
    "venue_id": 3,
    "artist_id": 6,
    "show_date": parse_date_string("2035-04-08T20:00:00.000Z")
    }, {
    "venue_id": 3,
    "artist_id": 6,
    "show_date": parse_date_string("2035-04-15T20:00:00.000Z")
    }]

    op.bulk_insert(
        show_table,
        show_data
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_genre_tags')
    op.drop_table('show')
    op.drop_table('artist_genre_tags')
    op.drop_table('venue')
    op.drop_table('artist')
    # ### end Alembic commands ###

